In [2]:
import numpy as np

In [4]:
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]
list_3 = [9,10,11,12]

In [5]:
sample_array = np.array([list_1,
                         list_2,
                         list_3])

In [6]:
print("Numpy Multi dimensional array in python\n", sample_array)

Numpy Multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print("Shape of the array :",
      sample_array.shape)

Shape of the array : (3, 4)


In [11]:
import pandas as pd

In [13]:
data = pd.read_csv('/content/sample_data/anscombe.json')

print(data.to_string())

                                          [
  {"Series":"I"    "X":10.0  "Y":8.04}  NaN
                   "X":8.0   "Y":6.95}  NaN
                   "X":13.0  "Y":7.58}  NaN
                   "X":9.0   "Y":8.81}  NaN
                   "X":11.0  "Y":8.33}  NaN
                   "X":14.0  "Y":9.96}  NaN
                   "X":6.0   "Y":7.24}  NaN
                   "X":4.0   "Y":4.26}  NaN
                   "X":12.0  "Y":10.84} NaN
                   "X":7.0   "Y":4.81}  NaN
                   "X":5.0   "Y":5.68}  NaN
  {"Series":"II"   "X":10.0  "Y":9.14}  NaN
                   "X":8.0   "Y":8.14}  NaN
                   "X":13.0  "Y":8.74}  NaN
                   "X":9.0   "Y":8.77}  NaN
                   "X":11.0  "Y":9.26}  NaN
                   "X":14.0  "Y":8.10}  NaN
                   "X":6.0   "Y":6.13}  NaN
                   "X":4.0   "Y":3.10}  NaN
                   "X":12.0  "Y":9.13}  NaN
                   "X":7.0   "Y":7.26}  NaN
                   "X":5.0   "Y"

In [14]:
#creating  list
data=["Harry","Sam","Juliet","Robert","Max"]
#creating pandas Series
df=pd.Series(data)
#printing Series
print(df)

0     Harry
1       Sam
2    Juliet
3    Robert
4       Max
dtype: object


In [15]:
Code In R Programming

In [1]:
install.packages("readr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [2]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [5]:
if (!requireNamespace("readr", quietly = TRUE)) {
  install.packages("readr")
}
library(readr)

file_path <- "/content/sample_data/mnist_test.csv"

data <- read_csv(file_path)
head(data)


New names:
• `0` -> `0...2`
• `0` -> `0...3`
• `0` -> `0...4`
• `0` -> `0...5`
• `0` -> `0...6`
• `0` -> `0...7`
• `0` -> `0...8`
• `0` -> `0...9`
• `0` -> `0...10`
• `0` -> `0...11`
• `0` -> `0...12`
• `0` -> `0...13`
• `0` -> `0...14`
• `0` -> `0...15`
• `0` -> `0...16`
• `0` -> `0...17`
• `0` -> `0...18`
• `0` -> `0...19`
• `0` -> `0...20`
• `0` -> `0...21`
• `0` -> `0...22`
• `0` -> `0...23`
• `0` -> `0...24`
• `0` -> `0...25`
• `0` -> `0...26`
• `0` -> `0...27`
• `0` -> `0...28`
• `0` -> `0...29`
• `0` -> `0...30`
• `0` -> `0...31`
• `0` -> `0...32`
• `0` -> `0...33`
• `0` -> `0...34`
• `0` -> `0...35`
• `0` -> `0...36`
• `0` -> `0...37`
• `0` -> `0...38`
• `0` -> `0...39`
• `0` -> `0...40`
• `0` -> `0...41`
• `0` -> `0...42`
• `0` -> `0...43`
• `0` -> `0...44`
• `0` -> `0...45`
• `0` -> `0...46`
• `0` -> `0...47`
• `0` -> `0...48`
• `0` -> `0...49`
• `0` -> `0...50`
• `0` -> `0...51`
• `0` -> `0...52`
• `0` -> `0...53`
• `0` -> `0...54`
• `0` -> `0...55`
• `0` -> `0...56`
• `0` -

7 0...2 0...3 0...4 0...5 0...6 0...7 0...8 0...9 0...10 ⋯ 0...776 0...777
1 2 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
2 1 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
3 0 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
4 4 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
5 1 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
6 4 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
  0...778 0...779 0...780 0...781 0...782 0...783 0...784 0...785
1 0       0       0       0       0       0       0       0      
2 0       0       0       0       0       0       0       0      
3 0       0       0       0       0       0       0       0      
4 0       0       0       0       0       0       0       0      
5 0       0       0       0       0       0       0       0      
6 0       0       0       0       0       0       0       0

In [4]:
# Install and load the dplyr library
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
library(dplyr)

# Create a sample data frame
data <- data.frame(
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(25, 30, 22),
  City = c("New York", "San Francisco", "Los Angeles")
)

# Display the original data frame
cat("Original Data Frame:\n")
print(data)

# Use dplyr to filter and summarize data
filtered_data <- data %>%
  filter(Age > 25) %>%
  mutate(Age_Squared = Age^2)

# Display the filtered and summarized data
cat("\nFiltered and Summarized Data:\n")
print(filtered_data)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




Original Data Frame:
     Name Age          City
1   Alice  25      New York
2     Bob  30 San Francisco
3 Charlie  22   Los Angeles

Filtered and Summarized Data:
  Name Age          City Age_Squared
1  Bob  30 San Francisco         900
